apiVersion: v1
kind: Service
metadata:
  name: frontphp-redis
  labels:
    app: frontphp
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: 
  type: ClusterIP