apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontphp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontphp
  template:
    metadata:
      labels:
        app: frontphp
    spec:
      volumes: 
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: site.conf
      - name: appcode
        emptyDir: {}  
      initContainers:
      - name: init-cpcode
        image: ariel1088/otrium:v2.1
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', "cp -r /app/. /var/www/html"]      
        volumeMounts:
        - name: appcode
          mountPath: /var/www/html
      containers:
      - name: frontphp
        image: ariel1088/otrium:v2.1
        envFrom:
        - configMapRef:
            name: frontphp-env-vars
        volumeMounts:
        - name: appcode
          mountPath: /var/www/html
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: appcode
          mountPath: /var/www/html
        - name: config
          mountPath: /etc/nginx/conf.d