apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontphp
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /count
        pathType: Prefix
        backend:
          service: 
            name: frontphp
            port: 
              name: fastcgi